name: Python_pipeline
on:
  push:
    branches:
      - master

jobs:
  checkstyle_project:
#    needs: name_jobs
    runs-on: ubuntu-latest

    steps:
      - name: Git clone repo
        uses: actions/checkout@v2

      - name: Set version Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.10'

      - name: Install dependencies python
        run: |
          pip install -r requirements.txt
          python -m pip install -r .github/workflows/requirements.txt
          python .github/workflows/ci.py

      - name: Check style project
#        continue-on-error: true
        run: |
          pip install pycodestyle
          pycodestyle .
